name: Trees CI
on:
  push:
    branches:
      - task-4

  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout project sources
      working-directory: ./4-Parallel-Trees
      uses: actions/checkout@v4

    - name: Setup gradle
      working-directory: ./4-Parallel-Trees
      uses: gradle/gradle-build-action@v2

    - name: Build
      working-directory: ./4-Parallel-Trees
      run: ./gradlew build

    - name: Test
      working-directory: ./4-Parallel-Trees
      run: ./gradlew test
